pub(crate) mod vector3;
pub(crate) mod material;
pub(crate) mod vector4;
pub(crate) mod ray;
pub(crate) mod object;
pub(crate) mod sphere;
pub(crate) mod intersection;
mod camera;
mod scene;
mod light;